Add laravel 8 support
avto-dev/amqp-rabbit-laravel-queue pull request #20
Opened 2021-04-14 11:54 UTC by bend-is

## Description

### Changed

- Minimal required PHP version now is `7.3`
- Minimal `symfony/*` version now is `5.1`
- Minimal `illuminate/*` package versions now is `8.0`
- Minimal `laravel/laravel` package versions now is `8.0`
- Minimal `phpunit/phpunit` package versions now is `9.3`
- Minimal `avto-dev/amqp-rabbit-manager` package versions now is `2.3`
- Version of `php` in docker container updated up to `7.3`
- Version of `composer` in docker container updated up to `2.0.12`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

2021-04-15 07:20 UTC, eldario requested changes

2021-04-15 07:20 UTC, eldario commented on src/Worker.php
> +    /** @var string */
- Split by lines
- Change to `string|null`

2021-04-15 07:20 UTC, eldario commented on src/Worker.php
> +                                string $consumer_tag = '')
change to
```php
?string $consumer_tag = null
```

2021-04-15 07:20 UTC, eldario commented on src/Worker.php
> +            if ($this->consumer_tag) {
```php
if ($this->consumer_tag !== null) {
```

2021-04-15 07:20 UTC, eldario commented on Dockerfile
>      COMPOSER_ALLOW_SUPERUSER="1" \
Remove `COMPOSER_ALLOW_SUPERUSER`

> 
> 1.9.1 2019-11-01
> 
> ...
>     Fixed root warnings always present in Docker containers, setting `COMPOSER_ALLOW_SUPERUSER` is not necessary anymore
> ...

2021-04-15 07:20 UTC, eldario commented on README.md
> +The prefix of the consumer queue tag can be specified with an additional argument in the `AvtoDev\AmqpRabbitLaravelQueue\Worker::__construct` method.
Add something more about this feature.

2021-04-15 07:20 UTC, eldario commented on src/Worker.php
> +     * Listen to the given queue in a loop.
Delete it, leave only this line
```
@inheritdoc
```

2021-04-15 10:48 UTC, bend-is commented on src/Worker.php
> +    /** @var string */
Done

2021-04-15 10:48 UTC, bend-is commented on src/Worker.php
> +                                string $consumer_tag = '')
Done

2021-04-15 10:48 UTC, bend-is commented on src/Worker.php
> +            if ($this->consumer_tag) {
Done

2021-04-15 10:48 UTC, bend-is commented on Dockerfile
>      COMPOSER_ALLOW_SUPERUSER="1" \
Done

2021-04-15 10:48 UTC, bend-is commented on README.md
> +The prefix of the consumer queue tag can be specified with an additional argument in the `AvtoDev\AmqpRabbitLaravelQueue\Worker::__construct` method.
Done

2021-04-15 10:48 UTC, bend-is commented on src/Worker.php
> +     * Listen to the given queue in a loop.
Done

2021-04-15 11:19 UTC, eldario commented on src/Worker.php
> +     * @param string $consumer_tag
```suggestion
     * @param ?string $consumer_tag
```

2021-04-16 06:41 UTC, eldario commented on src/Worker.php
> +    /** @var string|null */
```suggestion
    /**
     * @var string|null
     */
```

2021-04-16 06:49 UTC, eldario approved these changes

2021-04-16 06:49 UTC, eldario commented
Thanx for your PR, @bend-is

2021-04-16 06:50 UTC, merged